### ISSUE TITLE
Error loading the package with Angular 7

### ISSUE THREAD

**Issue by tkapitein** [realappie/ngx-intl#4]
Getting this error on Angular 7:
```
Uncaught TypeError: Object(...) is not a function
    at ngx-intl.js:56
```

Also some compile warnings: 
`./node_modules/ngx-intl/fesm5/ngx-intl.js
56:139-147 "export 'ɵɵinject' was not found in '@angular/core'`

`client:154 ./node_modules/ngx-intl/fesm5/ngx-intl.js
56:53-71 "export 'ɵɵdefineInjectable' was not found in '@angular/core'`

**Comment by realappie** [comment]
This package only works with angular +8, we will have to see how we can add support for angular 7. Perhaps see if we can build the library for angular 7 too, although I would rather support angular 8+ to keep build complexity low.
